# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba277eeae96573ee1f5caa4de05399c95ca1db3c7cdd1df6e864d20dec3ecbdf9d2e6ec99f04373779b94a6608f09023966c6623b747974250b49b6e5926743b

test:
  secret_key_base: 5bc33136ceec9cf456b4c88f7af3ef5cbf1ec76ee028d9fca22b0abaacc99a6e9ac9b37bab6f20d420384da7dd4191a689046cb40482e03dd2dffd2e8c7e76c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production: